version: '3.7'
services:
  nest:
    build: ./nest-backend

    ports:
      - "5000:3000"
    volumes:
      - "/usercode/:/code"
    environment:
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USERNAME=admin
      - DB_PASSWORD=admin
      - DB_NAME=blog_DB
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  db:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=blog_DB
    ports:
      - "5432:5432"
  vue:
    build: ./vue3-frontend

    ports:
      - "80:8080"

    volumes:
      - "/usercode/:/code"
