version: '3.7'
services:
  nest:
    build: ./nest-backend
    command: sh -c "cd /app && npm install && npm run build && npm run start:dev"
    ports:
      - "5000:3000"
    volumes:
      - "./nest-backend:/app"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=admin
      - DB_PASSWORD=admin
      - DB_NAME=blog_DB
    depends_on:
       - db
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  db:
    image: postgres:15.3
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=blog_DB
      - POSTGRES_HOST=127.0.0.1
    ports:
      - "5432:5432"
  vite:
    image: node:14
    command: sh -c "cd /app && npm install && npm run dev"
    ports:
      - "80:3000"
    volumes:
      - "./vue3-frontend:/app"